In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

In [11]:
d0 = "the dog chased the cat"
d1 = "the cat chased the mouse"
d2 = "the mouse chased the dog"

In [12]:
d0 = d0.lower().split(" ")
d1 = d1.lower().split(" ")
d2 = d2.lower().split(" ")

vocab = d0 + d1 + d2

In [23]:
OneHotEnc = OneHotEncoder(sparse=False)
OneHotMatrix = OneHotEnc.fit_transform(np.array(vocab).reshape(-1,1))

In [24]:
print(OneHotMatrix)

[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
